### ISSUE TITLE
it doesn't react to my beautify save action

### ISSUE THREAD

**Issue by e-cloud** [ForbesLindesay/brackets-globals#5]
I use another extension beautify. After I save and auto-format the js file, 'globals' doesn't seem take effect, there is no red text any more.Until i tab out and back to the file, it works. Should it listen to file refresh(i guess) or other changes?

**Comment by NoAnyLove** [comment]
Have the same issue, the red text will lose efficacy if I use Brackets Beautify format the JavaScript file.
